### ISSUE TITLE
Colors on multiple SVGs

### ISSUE THREAD

**Issue by Soean** [englishextra/qrjs2#4]
`textcolor` and `fillcolor` are not working with more then one QR-Code on a page. Styles in Inline SVG aren't Scoped.

See: https://codepen.io/soerenwrede/pen/ZXZVpE

**Comment by englishextra** [comment]
@Soean Thanks for pointing that out.

Sadly: [The scope attribute has been removed from the current specification.](http://caniuse.com/#feat=style-scoped)

What can be done is to **give svg a unique id and use that in embedded into svg style tag**

So:

```
<svg viewBox="0 0 66 66" style="shape-rendering:crispEdges" id="svg1"><style>#svg1 .bg{fill:#FFFFFF}#svg1 .fg{fill:#00ff00}</style>

<svg viewBox="0 0 66 66" style="shape-rendering:crispEdges" id="svg2"><style>#svg2 .bg{fill:#FFFFFF}#svg2 .fg{fill:#ff00ff}</style>
```
[jsfiddle](https://jsfiddle.net/englishextra/bs1pjc08/)

Are you willing to add your JS changes / PR or would you like me to think that over?

**Comment by Soean** [comment]
Hey @englishextra, thanks for your answer :-)
Yes, I also found the removed scope attribute. Right now, I have no real solution. I built a wrapper around the svgs for my own project.

**Comment by englishextra** [comment]
@Soean 

[tested in Chrome / Edge / Firefox and as you know for IE11 there's a fallback to PNG](https://jsfiddle.net/englishextra/qexw1ct1/)

I'll updated npm and bower very soon.

**Comment by Soean** [comment]
@englishextra 
Thanks, works great!

**Comment by englishextra** [comment]
Updated at [npm](https://www.npmjs.com/~englishextra)

## CDN
#### jsDelivr
`https://cdn.jsdelivr.net/gh/englishextra/qrjs2@0.1.6/qrjs2.min.js`

#### unpkg
`https://unpkg.com/qrjs2@0.1.6/qrjs2.js`
